CREATE TABLE users (
    user_id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(1000) NOT NULL,
    email VARCHAR(250) NOT NULL UNIQUE REFERENCES login(email),
    joined DATE NOT NULL DEFAULT CURRENT_DATE
);